### PR TITLE
Add support to custom_char

### PR DESCRIPTION
**Pull request by marado**
As a step closer to  #10, this commit adds support to custom_char.

### CODE REVIEW

**Comment by kablamo** [comment]
Interesting.  Why do you want this feature?  Got an example?

**Comment by kablamo** [comment]
Oh I guess it makes sense for Term::Vspark.  If your terminal doesn't support utf8.  It would be much less useful for Term::Spark, right?

**Comment by marado** [comment]
[replying to your first comment]
This can be used (I actually do - a variant of it) on services where you want to avoid the use utf8 characters, for instance for telnet-based services.

[after reading your second comment]
Yes, this is useful in cases where there isn't utf8 support, or where its support isn't guaranteed. I use this only in a Vspark scenario, but I actually can see this as potentially useful on a Spark scenario too - why not?

**Comment by marado** [comment]
BTW, after having a deja-vu moment, I went looking and... here's the original discussion :-)
https://github.com/LuRsT/vspark/pull/2

**Comment by LuRsT** [comment]
I'm glad this is taking off :+1:

**Comment by kablamo** [comment]
Wow I totally don't remember that.  Cool.  I'm going to merge this.  

In the future if you could do prs in a branch thatd be cool.  So I can pull it down and test it before merging.   Actually I didn't know you could do prs from master.

**Comment by kablamo** [comment]
Also fyi I plan to create a vspark script thats part of this dist.  And a spark script thats part of Term::Spark

**Pull request merged**
