### PR TITLE
Kvalues

### PR DESCRIPTION
**Pull request by kablamo**
I didn't intend to take this approach to the problem.  I wrote the solution we discussed, but I kept having the feeling it was overly complicated.

So I went back and tried it like this and felt like the outcome felt good and made the code simpler and api simpler.  

Maybe I should push the other solution so you can compare the two except I'd have to write it again because I didn't keep a copy.

I wonder how other graphing tools handle these inputs.  I'm sure lots of people have dealt with this problem before.

### CODE REVIEW

**Comment by kablamo** [comment]
ping @LuRsT this version hasn't been released to cpan.  any chance you could do that?

**Comment by LuRsT** [comment]
Hi @kablamo, thanks for the reminder, I'll see if I can release it later, haven't done anything with cpan lately, hopefully I'll remember how to do it :P

**Comment by LuRsT** [comment]
Hey @kablamo, I just remembered this, since I haven't got time to deal with this, would you be happy to be the maintainer of the two packages? Term::Vspark and Term::Spark?

**Comment by kablamo** [comment]
Sure I would be happy to.  Here are the steps for changing ownership of a CPAN module:

1. Go to http://pause.perl.org (its a very old and ugly site)
2. Click the login link in the left hand menu
3. Select 'Change Permissions' from the left hand menu
4. On this screen you can either add me as a co maintainer or transfer ownership entirely to me.  Up to you.

My PAUSE username is KABLAMO.  After that I can just clone your repo.  If you have any questions let me know.

**Comment by LuRsT** [comment]
Thanks for the instructions mate, all done. Apparently I'm not the main owner, but I made you co-maintainer of both projects. I tried transfering these repos to you here on github but since you have forks with the same name, it didn't let me. I'm happy to transfer them to you, unless you really don't want to.

**Comment by kablamo** [comment]
Awesome thanks!  I deleted my forks so you can transfer the repos.

Appreciate you doing all this effort.  Sorry to see you go off into the Python world.  :)

**Comment by LuRsT** [comment]
Hahaha, it was always the plan :)

**Comment by LuRsT** [comment]
Done, you may now give them the love they deserve :grinning:

**Comment by kablamo** [comment]
Hmm I'm still seeing this repo as belonging to you and not to me.  Do you see something different?

**Comment by LuRsT** [comment]
Me too, but it said that I sent an invite to transfer, so you probably need to accept it. Don't ask me where. Did you get something?

**Comment by kablamo** [comment]
Oh yeah.  I got an email.  It was just slow.  It worked now.  Thanks!

**Comment by LuRsT** [comment]
Awesome :star: !

**Pull request merged**
